-- ============================================================================
-- General domain — reverse-direction library seeds (FA→EN, FR→EN)
-- ============================================================================
--
-- Context: T0/T2 seeded General × 3 difficulties only in the FORWARD direction
-- (EN→FA, EN→FR). The Persian-source applications surfaced in admin had no
-- matching test in the library, so the preview step showed "no test available"
-- for every General combination on those apps.
--
-- This migration adds the reverse-direction rows: 2 source pairs (FA, FR)
-- × 3 difficulties = 6 rows, all under domain='general'. Both source_text and
-- reference_translation land NULL — cvp-seed-library-refs (already supports
-- source_text generation as of T4) fills them in and flips is_active=true on
-- success. AI fallback rule applies: failures leave the row inactive with an
-- ai_generation_error and do not abort the run.
--
-- Title-stems and instructions mirror the forward-direction General seeds so
-- the seeder produces equivalent content types in the source language. The
-- "preserve names" / "register" guidance is reframed for an English target.
-- ============================================================================

BEGIN;

WITH pairs(src_id, tgt_id, label) AS (
  VALUES
    ('d972e8cc-519c-4446-9483-30da1346850c'::uuid,  -- Persian (Farsi)
     'fde091d2-db5f-4e41-a490-7e15efc419e1'::uuid,  -- English
     'FA→EN'),
    ('3f020964-31f9-4310-b632-a46fb629231a'::uuid,  -- French
     'fde091d2-db5f-4e41-a490-7e15efc419e1'::uuid,  -- English
     'FR→EN')
),
sources AS (
  SELECT
    'beginner'::text AS difficulty,
    'General — Personal letter'::text AS title_stem,
    $INST$Translate this personal letter into English, preserving the warm and conversational tone throughout.
- Use an informal but natural English register appropriate for close friends — contractions are fine.
- Keep all proper names unchanged.
- Preserve the letter's structure — greeting, body paragraphs, sign-off.
- Idioms in the source should be rendered with their natural English equivalent, not word-for-word.
- If the source uses a culture-specific reference that has no clean English match, choose the closest natural reading; do not over-explain.$INST$::text AS instructions,
    '{"accuracy":0.20,"terminology":0.10,"fluency":0.35,"style":0.20,"locale":0.10,"design":0.00,"non_translation":0.05}'::jsonb AS rubric

  UNION ALL

  SELECT
    'intermediate',
    'General — Internal HR announcement',
    $INST$Translate this internal HR communication into English. The audience is the full employee base of an English-speaking office — register is professional but approachable.
- Preserve all specific figures, dates, and programme names exactly. Convert currency notations to standard English form (e.g. "$500", "1 June 2025").
- Programme names that have an established English equivalent should use it; otherwise transliterate or translate on first mention with the original in parentheses.
- Maintain the collaborative "we" voice throughout.
- Preserve the subject line format and the sign-off structure.
- Use English business-English conventions for headings and bullet punctuation.$INST$,
    '{"accuracy":0.25,"terminology":0.20,"fluency":0.20,"style":0.20,"locale":0.10,"design":0.00,"non_translation":0.05}'::jsonb

  UNION ALL

  SELECT
    'advanced',
    'General — Op-ed on urban transit',
    $INST$Translate this opinion column into English for a quality-newspaper audience. Register is formal-journalistic with a clear authorial voice.
- Preserve named places, transit-system names, and official statistics exactly. If a place name has a conventional English exonym (e.g. "Tehran", "Marseille"), use it.
- The author's argumentative voice — irony, rhetorical questions, hedged claims — must come through in idiomatic English, not be flattened.
- Quoted sources or named individuals stay attributed. Do not summarise quotes; translate them in full.
- Preserve paragraph breaks and any em-dashes used for emphasis.
- Use UK or US English consistently — pick whichever the source's likely target market would read and stick with it.$INST$,
    '{"accuracy":0.25,"terminology":0.20,"fluency":0.20,"style":0.20,"locale":0.10,"design":0.00,"non_translation":0.05}'::jsonb
)
INSERT INTO cvp_test_library (
  id, title,
  source_language_id, target_language_id,
  domain, service_type, difficulty,
  source_text, instructions,
  reference_translation, ai_assessment_rubric,
  is_active, times_used
)
SELECT
  gen_random_uuid(),
  '[AI-DRAFT] ' || s.title_stem || ' (' || p.label || ')',
  p.src_id,
  p.tgt_id,
  'general',
  'domain_test',
  s.difficulty,
  NULL,                   -- source_text — generated by cvp-seed-library-refs
  s.instructions,
  NULL,                   -- reference_translation — generated by cvp-seed-library-refs
  s.rubric,
  false,                  -- flipped to true once AI generation completes
  0
FROM sources s, pairs p
ON CONFLICT (id) DO NOTHING;

COMMIT;

-- Verification — should return 6 rows (3 difficulties × 2 reverse pairs)
SELECT
  difficulty,
  title,
  is_active,
  (source_text IS NOT NULL) AS has_source,
  (reference_translation IS NOT NULL) AS has_ref
FROM cvp_test_library
WHERE domain = 'general'
  AND source_language_id <> 'fde091d2-db5f-4e41-a490-7e15efc419e1'::uuid
ORDER BY difficulty, title;
